name: Android CI

on:
  push:
    branches:
      - main
      - multi-module
  pull_request:
    branches:
      - multi-module

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [assembleDebug, testDebugUnitTest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          components: build-tools;34.0.0

      - name: Build and Test Target
        run: ./gradlew ${{ matrix.target }} --no-daemon

      - name: Upload Build Outputs
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: app/build/outputs

  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          components: build-tools;34.0.0

      - name: Run ktlint
        run: |
          ./gradlew ktlintFormat --no-daemon
          ./gradlew ktlintCheck --no-daemon
