name: MultiModule Workflow

on:
  push:
    branches:
      - main_disabled
      - multi-module_disabled
  pull_request:
    branches:
      - multi-module_disabled

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [ 21, 29, 23 ] # Test on different API levels
        target: [ assembleDebug ] # Build and unit test tasks
        module: [ app, core-ui] #, core-util, feature-auth, core-data, feature-posts, feature-profile ]  # Modules

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build app
        run: ./gradlew ${{ matrix.target }} --no-daemon

#      - name: Run UI tests
#        run: |
#          cd ${{ matrix.module }}
#          ./gradlew connectedDebugAndroidTest
