name: MultiModule Workflow

on:
  push:
    branches:
      - main
      - multi-module
  pull_request:
    branches:
      - multi-module

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [ 21, 29, 23 ] # Test on different API levels
        target: [ assembleDebug, testDebugUnitTest ] # Build and unit test tasks
        include:
          - module: app
          - module: core-ui
          - module: core-util
          - module: feature-auth
          - module: core-data
          - module: feature-posts
          - module: feature-profile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build and test
        run: |
          cd ${{ matrix.module }}
          ./gradlew assembleDebug

      - name: Run unit tests
        run: |
          cd ${{ matrix.module }}
          ./gradlew testDebugUnitTest

#      - name: Run UI tests
#        run: |
#          cd ${{ matrix.module }}
#          ./gradlew connectedDebugAndroidTest
